FROM node:22-alpine

# Install pnpm
RUN npm install -g pnpm

WORKDIR /usr/src/app

# Copy package files
COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/web ./apps/web

# Install dependencies
RUN pnpm install
RUN pnpm run db:generate
RUN pnpm run build


EXPOSE 3000

# Start the web application
CMD ["pnpm", "start:web"]